// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7FWpndImSPZEURzkKiFKcDRoDWVWMeU',
    appId: '1:593586705791:web:46a39e5c9f3c5d8ab8364a',
    messagingSenderId: '593586705791',
    projectId: 'new-event-booking',
    authDomain: 'new-event-booking.firebaseapp.com',
    storageBucket: 'new-event-booking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgUczcMnBssLWERyF3PZExwhDghYwg90I',
    appId: '1:593586705791:android:7f3008929aa5c303b8364a',
    messagingSenderId: '593586705791',
    projectId: 'new-event-booking',
    storageBucket: 'new-event-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Ijta_PhgYWCDX-xOVGf-OT7O2Kz5c9U',
    appId: '1:593586705791:ios:c6374438c84b1c8bb8364a',
    messagingSenderId: '593586705791',
    projectId: 'new-event-booking',
    storageBucket: 'new-event-booking.firebasestorage.app',
    iosBundleId: 'com.example.newEventBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Ijta_PhgYWCDX-xOVGf-OT7O2Kz5c9U',
    appId: '1:593586705791:ios:c6374438c84b1c8bb8364a',
    messagingSenderId: '593586705791',
    projectId: 'new-event-booking',
    storageBucket: 'new-event-booking.firebasestorage.app',
    iosBundleId: 'com.example.newEventBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP7FWpndImSPZEURzkKiFKcDRoDWVWMeU',
    appId: '1:593586705791:web:6de5d4160d0555adb8364a',
    messagingSenderId: '593586705791',
    projectId: 'new-event-booking',
    authDomain: 'new-event-booking.firebaseapp.com',
    storageBucket: 'new-event-booking.firebasestorage.app',
  );
}
